import React from 'react';
import {
  AboutContainer,
  AboutTitle,
  ImageCard,
  MarqueeContainer,
  MarqueeText,
  SpanClose,
  SpanTitle,
  TextMessinaBig,
  TextMessinaLitle,
} from './About.styled';
import AboutImage from '../../assets/image/layer-5apv-1herox2-6653a3fa625a0.webp';

const About: React.FC = () => {
  return (
    <>
      <AboutContainer id="about">
          <AboutTitle>
            a Story that started with <SpanTitle>one simple <br/> ape</SpanTitle>
          </AboutTitle>
          <TextMessinaBig>
            WHO GOT<br/> FED UP WITH BORING AND HYPOCRITIC COMMONPLACE THIS IS HOW
            THE IDEA OF ESCAPING AND DYNAMIC JOURNEY ON THE YACHT
          </TextMessinaBig>
          <SpanClose>✖️</SpanClose>
          <TextMessinaLitle>
            EACH ARTWORK IN THE COLLECTION TELLS A STORY OF ONE JOURNEY. ARTS
            ARE RANDOMLY GENERATED BY USERS
          </TextMessinaLitle>
          <ImageCard src={AboutImage} alt="Image NFT" />
      </AboutContainer>
      <MarqueeContainer>
        <MarqueeText>
          ✖️ HAVE NO LIMITS ✖️ HAVE NO LIMITS ✖️ HAVE NO LIMITS ✖️ HAVE NO
          LIMITS ✖️ HAVE NO LIMITS ✖️ HAVE NO LIMITS ✖️ HAVE NO LIMITS ✖️ HAVE
          NO LIMITS ✖️ HAVE NO LIMITS ✖️ HAVE NO LIMITS ✖️ HAVE NO LIMITS ✖️
        </MarqueeText>
      </MarqueeContainer>
    </>
  );
};

export default About;
